planning_pipelines:
  pipeline_names: ["ompl"]

plan_request_params:
  planning_attempts: 10
  planning_pipeline: ompl
  planner_id: "RRTConnectkConfigDefault"
  max_velocity_scaling_factor: 0.3
  max_acceleration_scaling_factor: 0.3
  planning_time: 15.0
