foundationpose_node:
  ros__parameters:
    mesh_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/ros2_ws/src/pose_estimation_pkg/meshes/sugar_box/textured.obj"
    weights_dir: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/FoundationPose/weights"
    score_threshold: 0.3
    debug_visualization: true

sam2_node:
  ros__parameters:
    checkpoint_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/sam2/checkpoints/sam2.1_hiera_small.pt"
    model_config: "sam2.1_hiera_small"
    segmentation_rate_hz: 5.0
    prompt_point_x: 0.5
    prompt_point_y: 0.5
    confidence_threshold: 0.7