foundationpose_node:
  ros__parameters:
    mesh_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/ros2_ws/src/pose_estimation_pkg/meshes/sugar_box/textured.obj"
    weights_dir: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/FoundationPose/weights"
    score_threshold: 0.3
    debug_visualization: true

sam2_node:
  ros__parameters:
    checkpoint_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/sam2/checkpoints/sam2.1_hiera_small.pt"
    model_config: "sam2.1_hiera_small"
    segmentation_rate_hz: 5.0
    prompt_point_x: 0.50
    prompt_point_y: 0.57
    confidence_threshold: 0.7

grasp_executor:
  ros__parameters:
    robot_name: "ur5e"
    planning_group: "ur_manipulator"
    end_effector_link: "tool0"
    pre_grasp_height: 0.15
    pose_stability_count: 10
    planning_time: 5.0
    max_velocity_scaling: 0.3

benchmark_node:
  ros__parameters:
    mesh_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/ros2_ws/src/pose_estimation_pkg/meshes/sugar_box/textured.obj"
    results_dir: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/results"
    num_samples: 200
    warmup_frames: 30