foundationpose_node:
  ros__parameters:
    mesh_path: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/ros2_ws/src/pose_estimation_pkg/meshes/sugar_box/textured.obj"
    weights_dir: "/home/samanth-krishna/projects/ros2_ws/src/foundationpose-ros2/FoundationPose/weights"
    score_threshold: 0.3
    debug_visualization: true